In [13]:
import numpy as np

In [14]:
class Node:
    def __init__(self, v=None):
        self.value = v
        self.next = None
        return
    
    def isempty(self):
        if self.value == None:
            return(True)
        else:
            return(False)

In [15]:
l1 = Node()
print(l1.isempty())

True


In [16]:
l2 = Node(5)
print(l2.isempty())

False


In [17]:
class Node:
    def __init__(self, v=None):
        self.value = v
        self.next = None
        return
    
    def isempty(self):
        if self.value == None:
            return(True)
        else:
            return(False)
        
    def append(self,v):
        # append, recursive
        if self.isempty():
            self.value = v
        elif self.next == None:
            self.next = Node(v)
        else:
            self.next.append(v)
        return

In [18]:
class Node:
    def __init__(self, v=None):
        self.value = v
        self.next = None
        return
    
    def isempty(self):
        if self.value == None:
            return(True)
        else:
            return(False)
        
    def append(self,v):
        # append, recursive
        if self.isempty():
            self.value = v
        elif self.next == None:
            self.next = Node(v)
        else:
            self.next.append(v)
        return
        
    def appendi(self,v):
        # append, iterative
        if self.isempty():
            self.value = v
            return
        temp = self
        while temp.next != None:
            temp = temp.next
        temp.next = Node(v)
        return

In [19]:
class Node:
    def __init__(self, v=None):
        self.value = v
        self.next = None
        return
    
    def isempty(self):
        if self.value == None:
            return(True)
        else:
            return(False)
        
    def insert(self,v):
        if self.isempty():
            self.value = v
            return
        
        newnode = Node(v)

        # Exchange values in self and newnode
        (self.value, newnode.value) = (newnode.value, self.value)

        # Switch links
        (self.next, newnode.next) = (newnode, self.next)

        return

In [20]:
class Node:
    def __init__(self, v=None):
        self.value = v
        self.next = None
        return
    
    def isempty(self):
        if self.value == None:
            return(True)
        else:
            return(False)
        
    def delete(self,v):
        # delete, recursive

        if self.isempty():
            return
        
        if self.value == v:
            self.value = None
            if self.next != None:
                self.value = self.next.value
                self.next = self.next.next
            return
        else:
            if self.next != None:
                self.next.delete(v)
                if self.next.value == None:
                    self.next = None
        
        return

In [21]:
class Node:
    def __init__(self, v=None):
        self.value = v
        self.next = None
        return
    
    def isempty(self):
        if self.value == None:
            return(True)
        else:
            return(False)
        
    def append(self,v):
        # append, recursive
        if self.isempty():
            self.value = v
        elif self.next == None:
            self.next = Node(v)
        else:
            self.next.append(v)
        return
        
    def appendi(self,v):
        # append, iterative
        if self.isempty():
            self.value = v
            return
        temp = self
        while temp.next != None:
            temp = temp.next
        temp.next = Node(v)
        return
    
    def insert(self,v):
        if self.isempty():
            self.value = v
            return
        
        newnode = Node(v)

        # Exchange values in self and newnode
        (self.value, newnode.value) = (newnode.value, self.value)

        # Switch links
        (self.next, newnode.next) = (newnode, self.next)

        return
    
    def delete(self,v):
        # delete, recursive

        if self.isempty():
            return
        
        if self.value == v:
            self.value = None
            if self.next != None:
                self.value = self.next.value
                self.next = self.next.next
            return
        else:
            if self.next != None:
                self.next.delete(v)
                if self.next.value == None:
                    self.next = None
        
        return
    
    def deletei(self,v):
        # delete, iterative

        if self.isempty():
            return
        
        if self.value == v:
            if self.next == None:
                self.value = None
            else:
                self.value = self.next.value
                self.next = self.next.next
            return
        
        temp = self
        
        while temp.next != None:
            if temp.next.value == v:
                temp.next = temp.next.next
                return
            else:
                temp = temp.next

        return

Implementation of lists in Python

In [22]:
# lists bad for matrix representation

zerolist = [0, 0 ,0]
zeromatrix = [zerolist, zerolist, zerolist]

print(zeromatrix)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [23]:
zeromatrix[1][1] = 1

print(zeromatrix)

[[0, 1, 0], [0, 1, 0], [0, 1, 0]]


In [30]:
zeromatrix = np.zeros(shape=(3,3))
print(zeromatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
newarray = np.array([[0,1],[1,0]])
print(newarray)

[[0 1]
 [1 0]]


In [ ]:
row2 = np.arange(5)
print(row2)

[0 1 2 3 4]


In [31]:
A = np.matrix([[1,2],[3,4]])
B = np.matrix([[5,6],[7,8]])

In [ ]:
C = 3*A + B
print(C)

[[ 8 12]
 [16 20]]


In [ ]:
D = np.matmul(A,B)
print(D)

[[19 22]
 [43 50]]
